#version: '3.8'

services:

      mysql:
          image: mysql:8
          container_name: mysql
          restart: always
          environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD}

          volumes:
            - './db:/var.lib.mysql'

          ports:
            - '${DB_PORT}:3306'

      phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'

        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: 'mysql'
            PMA_PORT: 3306
#          PMA_USER: 'admin'
#          PMA_PASSWORD: 'admin'
          #
        depends_on:
          - mysql